# Title
title: Atlas

# Global pixel size varibals on the canvas
dimensions :
  scale: 2
  hp: 256
  wp: 256

# Color palette for the window
background: '#262626'
primaryColor: '#2e2e2e'

white: '#ffffff'