# Title
title: Atlas

game :
  # Global window size variables
  dimensions :
    width: 1280
    height: 700
  fps: 120

software :
  # Global pixel size variables on the canvas
  dimensions :
    scale: 2
    hp: 256
    wp: 256
  # Color palette for the window
  colors :
    background : '#262626'
    primaryColor: '#2e2e2e'
    white: '#ffffff'
